# Custom Builder for GraalVM
# A custom builder is created to take advantage of using a custom run-image,
# which can be much smaller as it does not need to have Java installed.

description = "Builder for the GCF with GraalVM"

[[buildpacks]]
  id = "google.java.maven"
  uri = "maven.tgz"

[[buildpacks]]
  id = "google.java.graalvm"
  uri = "graalvm.tgz"

[[buildpacks]]
  id = "google.utils.archive-source"
  uri = "archive_source.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[order]]

  [[order.group]]
    id = "google.utils.archive-source"

  [[order.group]]
    id = "google.java.maven"

  [[order.group]]
    id = "google.java.graalvm"

  [[order.group]]
    id = "google.utils.label"

[stack]
  id = "google.java11"
  build-image = "gcr.io/gae-runtimes/buildpacks/java11/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/java11/run"

[lifecycle]
  version = "0.10.2"
